"""Canvas Common Cartridge page emitter.

`page.json` -> a Canvas `.imscc` course package whose pages import as **Wiki Pages**. Every
structure here is transcribed from a real Canvas course export (the ARGS260 export in `reference/`):

- A wiki page is a `type="webcontent"` resource pointing at `wiki_content/<slug>.html`.
- That HTML carries an exact `<head>` — a `<meta name="identifier">` matching its resource id, plus
  `editing_roles` / `workflow_state` — and a `<body>` of Canvas-safe HTML.
- The manifest uses the Common Cartridge (`imsccv1p1`) namespaces, not the QTI-Quiz-Export shape.

The body is the **same** themed, inline-styled HTML the standalone `.html` emitter renders — one
renderer, two delivery paths. This emitter only re-wraps it in the wiki-page envelope and packages
it. There is no model here: like QTI, it reads the neutral IR and emits.

**Why the Canvas-flavoured skeleton is load-bearing.** A bare package of `wiki_content/` webcontent
resources imports as *Files*, not Pages — Canvas only maps `wiki_content/` to Wiki Pages when it runs
its *own* importer, and the trigger for that is the presence of `course_settings/canvas_export.txt`
(a marker file; its content is irrelevant). So the package carries that marker, declared by a
`learning-application-resource` in the manifest, plus a `course_settings/module_meta.xml` that lists
each page as a `WikiPage` module item (which both guarantees page-ness and attaches the pages to one
module) and a matching `<organizations>` tree.

**Deliberately NOT shipped: `course_settings/course_settings.xml`.** That file carries course-level
title/settings; importing it would mutate the *target* course. This emitter only ever adds pages and
one module — it never rewrites a course's own settings.
"""

import hashlib
import zipfile
from pathlib import Path

# Canvas's own cccv1p0 namespace (module_meta.xml). Distinct from the IMS manifest namespaces.
CANVAS_NS = ('xmlns="http://canvas.instructure.com/xsd/cccv1p0" '
             'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
             'xsi:schemaLocation="http://canvas.instructure.com/xsd/cccv1p0 '
             'https://canvas.instructure.com/xsd/cccv1p0.xsd"')

# The marker whose *presence* makes Canvas run its Common-Cartridge importer (which imports
# wiki_content/*.html as Pages). Content is irrelevant to Canvas; we say what wrote it.
CANVAS_EXPORT_MARKER = (
    "Generated by coursekit. This marker tells Canvas to run its own Common Cartridge importer,\n"
    "which imports wiki_content/*.html as Wiki Pages rather than as Files.\n"
)

# Common Cartridge manifest namespaces — verbatim from the real export's <manifest> element.
# Note the manifest-level LOM (`lomimscc`), distinct from the resource-level LOM (`lom`); the
# QTI-Quiz-Export manifest used neither of these, so this is its own constant, not a shared one.
MANIFEST_NS = (
    'xmlns="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1" '
    'xmlns:lom="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource" '
    'xmlns:lomimscc="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest" '
    'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
    'xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1 '
    'http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imscp_v1p2_v1p0.xsd '
    'http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource '
    'http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lomresource_v1p0.xsd '
    'http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest '
    'http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lommanifest_v1p0.xsd"')


# ------------------------------------------------------------------- escaping

def _xml(s: str) -> str:
    """XML-escape text content. '&' first, so we never double-escape."""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _attr(s: str) -> str:
    """Escape for an XML attribute value."""
    return _xml(s).replace('"', "&quot;")


# ------------------------------------------- identifiers (deterministic)

def _h(*parts) -> str:
    return hashlib.md5(":".join(str(p) for p in parts).encode("utf-8")).hexdigest()


def gid(*parts) -> str:
    """A `g`-prefixed 32-hex id, stable for the same inputs — so a re-emit keeps ids steady."""
    return "g" + _h(*parts)


def page_ident(page) -> str:
    """The resource id for a page, which its wiki HTML echoes in `<meta name='identifier'>`."""
    return gid(page.page_id, "page")


def course_ident(course_title: str) -> str:
    """The id of the course_settings `learning-application-resource`."""
    return gid(course_title, "course")


def module_ident(course_title: str) -> str:
    """The id of the single module the pages are placed in."""
    return gid(course_title, "module")


def item_ident(page) -> str:
    """The id of a page's module item (distinct from the page resource it points at)."""
    return gid(page.page_id, "item")


# ---------------------------------------------------------------- the wiki page

_PAGE_HTML = """<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>{title}</title>
<meta name="identifier" content="{ident}"/>
<meta name="editing_roles" content="teachers"/>
<meta name="workflow_state" content="active"/>
</head>
<body>
{body}
</body>
</html>
"""


def render_page(page, supplements: dict | None = None, style: dict | None = None) -> str:
    """One wiki page's HTML: the Canvas meta header + the themed, inline-styled block body.

    The body is exactly what the `.html` emitter renders (via the shared page renderer), minus the
    standalone document's `<style>` wrapper — Canvas strips `<style>`, and the theme lives in inline
    attributes anyway. The page title is NOT repeated as a body heading: Canvas shows it as the page
    name (from `<title>`), matching the real exported pages.
    """
    from coursekit.generate.page.renderer import render_body
    body = render_body(page, supplements, style)
    return _PAGE_HTML.format(title=_xml(page.title), ident=page_ident(page), body=body)


def _page_href(page) -> str:
    return f"wiki_content/{page.slug}.html"


def page_resource(page) -> str:
    """The `webcontent` resource block wiring one page into the manifest."""
    ident, href = page_ident(page), _page_href(page)
    return (f'    <resource identifier="{ident}" type="webcontent" href="{href}">\n'
            f'      <file href="{href}"/>\n'
            f'    </resource>')


def _course_settings_resource(course_title: str) -> str:
    """The `learning-application-resource` that declares the course_settings bundle. Its href is the
    canvas_export.txt marker (Canvas keys the flip to Pages off that path); the <file> children are
    the settings files we actually ship."""
    return (f'    <resource identifier="{course_ident(course_title)}" '
            f'type="associatedcontent/imscc_xmlv1p1/learning-application-resource" '
            f'href="course_settings/canvas_export.txt">\n'
            f'      <file href="course_settings/canvas_export.txt"/>\n'
            f'      <file href="course_settings/module_meta.xml"/>\n'
            f'    </resource>')


# ------------------------------------------------------------- module placement

def emit_module_meta(pages, course_title: str) -> str:
    """`course_settings/module_meta.xml`: one module holding every page as a `WikiPage` item. The
    `content_type` is what tells Canvas each item is a page (not a file); `identifierref` points at
    the page's webcontent resource."""
    items = "\n".join(
        f'''      <item identifier="{item_ident(p)}">
        <content_type>WikiPage</content_type>
        <workflow_state>active</workflow_state>
        <title>{_xml(p.title)}</title>
        <identifierref>{page_ident(p)}</identifierref>
        <position>{i}</position>
        <new_tab>false</new_tab>
        <indent>0</indent>
        <link_settings_json>null</link_settings_json>
      </item>''' for i, p in enumerate(pages, 1))
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<modules {CANVAS_NS}>
  <module identifier="{module_ident(course_title)}">
    <title>{_xml(course_title)}</title>
    <workflow_state>active</workflow_state>
    <position>1</position>
    <require_sequential_progress>false</require_sequential_progress>
    <locked>false</locked>
    <items>
{items}
    </items>
  </module>
</modules>
'''


def _organizations(pages, course_title: str) -> str:
    """The IMS rooted-hierarchy that mirrors module_meta — one module, its pages as leaf items."""
    items = "\n".join(
        f'''          <item identifier="{item_ident(p)}" identifierref="{page_ident(p)}">
            <title>{_xml(p.title)}</title>
          </item>''' for p in pages)
    return f'''  <organizations>
    <organization identifier="org_1" structure="rooted-hierarchy">
      <item identifier="LearningModules">
        <item identifier="{module_ident(course_title)}">
          <title>{_xml(course_title)}</title>
{items}
        </item>
      </item>
    </organization>
  </organizations>'''


# ------------------------------------------------------------------- manifest

def emit_manifest(pages, course_title: str) -> str:
    """The Common Cartridge manifest: course metadata, the module organizations tree, the
    course_settings resource (the Canvas-importer trigger), and one webcontent resource per page."""
    manifest_id = gid(*[p.page_id for p in pages], "manifest")
    resources = "\n".join(page_resource(p) for p in pages)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="{manifest_id}" {MANIFEST_NS}>
  <metadata>
    <schema>IMS Common Cartridge</schema>
    <schemaversion>1.1.0</schemaversion>
    <lomimscc:lom>
      <lomimscc:general>
        <lomimscc:title>
          <lomimscc:string>{_xml(course_title)}</lomimscc:string>
        </lomimscc:title>
      </lomimscc:general>
    </lomimscc:lom>
  </metadata>
{_organizations(pages, course_title)}
  <resources>
{_course_settings_resource(course_title)}
{resources}
  </resources>
</manifest>
'''


# --------------------------------------------------------------- packaging

def package_files(entries: list[tuple], course_title: str) -> dict[str, str]:
    """The arcname -> content map for the `.imscc`: one wiki page per entry + the manifest.

    An entry is (page, supplements, style). A slug collision is an error, not a silent overwrite —
    two pages writing the same `wiki_content/<slug>.html` would drop one.
    """
    files: dict[str, str] = {}
    pages = []
    for page, supp, style in entries:
        href = _page_href(page)
        if href in files:
            raise ValueError(f"two pages produced the same file: {href} "
                             f"(slug '{page.slug}' is not unique)")
        files[href] = render_page(page, supp, style)
        pages.append(page)
    # the Canvas-importer trigger + module placement (see the module docstring)
    files["course_settings/canvas_export.txt"] = CANVAS_EXPORT_MARKER
    files["course_settings/module_meta.xml"] = emit_module_meta(pages, course_title)
    files["imsmanifest.xml"] = emit_manifest(pages, course_title)
    return files


def _week_order(page) -> tuple:
    """Sort key that orders week-2 before week-10 (numeric), not lexically — so the module's page
    order in Canvas follows the weeks. Non-week pages sort last, by slug. Matches how the course
    cartridge orders its week modules (`cartridge._week_sort`)."""
    from coursekit.courseconfig import week_key
    k = week_key(page.week_ref) if page.week_ref else None
    if k and k.isdigit():
        return (0, int(k), "")
    return (1, 0, page.week_ref or page.slug or "")


def _load_pages(path) -> list[tuple]:
    """Every committed `page.json` under `path`, each with its course supplements and theme, in
    week order.

    Mirrors `emit/html.reemit`: supplements and style are resolved at package time by walking up to
    the `.vtconfig/` root, so the cartridge carries the same styled body a re-render would.
    """
    from coursekit.courseconfig import find_root
    from coursekit.generate.page.page import Page
    from coursekit.generate.page.renderer import load_supplements
    from coursekit.generate.page.style import load_style

    entries = []
    for pj in sorted(Path(path).rglob("page.json")):
        page = Page.model_validate_json(pj.read_text(encoding="utf-8"))
        root = find_root(pj)
        supp = load_supplements(root, page.week_ref or page.slug)
        entries.append((page, supp, load_style(root)))
    entries.sort(key=lambda e: _week_order(e[0]))   # week-2 before week-10, not lexical
    return entries


def _course_title(path) -> str:
    """The course's title from its shared context, or a sensible default."""
    from coursekit.courseconfig import find_root, load
    root = find_root(Path(path))
    if root:
        title = load(root).course_title
        if title:
            return title
    return "Course Pages"


def write_imscc(path, out_path=None, title=None) -> Path | None:
    """Package every `page.json` under `path` into ONE Canvas `.imscc` — one import, all pages.

    Returns the written path, or None when there are no pages to package. Deterministic ids mean
    re-packaging the same course yields byte-stable ids.
    """
    entries = _load_pages(path)
    if not entries:
        return None

    course_title = title or _course_title(path)
    files = package_files(entries, course_title)  # may raise on a slug collision — before any I/O

    path = Path(path)
    if out_path is None:
        base = path if path.is_dir() else path.parent
        out_path = base / "pages.imscc"
    out_path = Path(out_path)
    if out_path.suffix != ".imscc":
        out_path = out_path.with_suffix(".imscc")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as z:
        for arc, data in files.items():
            z.writestr(arc, data)
    return out_path
